global:
  scrape_interval: 10s # polling interval

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['node:8080'] # where to look for /metrics, in docker network alias is 'node', thus no ip